name: KotlinPluginTemplate
version: 1.0.0
main: com.sfirew.dev.kotlin.plugintemplate.Main
description: SFireW Minecraft Template Plugin
author: SnowFireWolf
website: https://sfirew.com
api-version: '1.20'